version: '3.7'

services:
  postgres1:
    image: registry.redhat.io/rhel9/postgresql-16
    container_name: postgres1
    environment:
      POSTGRESQL_USER: cvadmin
      POSTGRESQL_PASSWORD_FILE: /run/secrets/pg_password_secret
      POSTGRESQL_DATABASE: db1
    volumes:
      - ./data1:/var/lib/pgsql/data:Z
    secrets:
      - pg_password_secret
    expose:
      - "5432"

  postgres2:
    image: registry.redhat.io/rhel9/postgresql-16
    container_name: postgres2
    environment:
      POSTGRESQL_USER: cvadmin
      POSTGRESQL_PASSWORD_FILE: /run/secrets/pg_password_secret
      POSTGRESQL_DATABASE: db2
    volumes:
      - ./data2:/var/lib/pgsql/data:Z
    secrets:
      - pg_password_secret
    expose:
      - "5432"

  haproxy:
    image: registry.redhat.io/rhceph/rhceph-haproxy-rhel9
    container_name: haproxy
    depends_on:
      - postgres1
      - postgres2
    ports:
      - "5432:5432"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

secrets:
  pg_password_secret:
    external: true
